"""Catalog of exercises and the muscle groups they train.

This module is the single source of truth for what the user can log: the
``/log`` picker, the API's accept-list, the weekly summary and the body map all
read from :data:`EXERCISES`.

The catalog itself is **data, not code**. ``app/data/exercises.json`` holds 873
movements vendored from `free-exercise-db
<https://github.com/yuhonas/free-exercise-db>`_ (Unlicense / public domain) and
is regenerated by ``tools/build_exercise_catalog.py``. Adding a movement by hand
is no longer the workflow; changing the pin and re-running the generator is.

Everything the file asserts about itself is checked at import — unique ids,
known muscle slugs, a non-empty ``primary``, exactly two images — so a bad
catalog fails at start-up rather than halfway through a summary.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

#: Muscle groups rendered on the body outline, in display order.
#:
#: The two silhouettes draw **disjoint** sets, so each carries information the
#: other does not. Front: chest, abs, shoulders, biceps, forearms, quads.
#: Back: back, traps, triceps, glutes, hamstrings, calves.
MUSCLE_GROUPS: tuple[str, ...] = (
    "chest",
    "abs",
    "shoulders",
    "biceps",
    "forearms",
    "quads",
    "back",
    "traps",
    "triceps",
    "glutes",
    "hamstrings",
    "calves",
)

#: Human readable labels for the muscle group slugs above.
MUSCLE_LABELS: dict[str, str] = {
    "chest": "Chest",
    "abs": "Abs",
    "shoulders": "Shoulders",
    "biceps": "Biceps",
    "forearms": "Forearms",
    "quads": "Quads",
    "back": "Back",
    "traps": "Traps",
    "triceps": "Triceps",
    "glutes": "Glutes",
    "hamstrings": "Hamstrings",
    "calves": "Calves",
}


#: Weekly set target for a large muscle group.
LARGE_MUSCLE_TARGET = 20

#: Weekly set target for a small muscle group, which recovers on less volume.
SMALL_MUSCLE_TARGET = 10

#: Sets per week each group is aiming for.  Reaching the target is the darkest
#: green; going past it starts the red overshoot scale (see
#: :func:`app.services.summary.grade`).
MUSCLE_TARGETS: dict[str, int] = {
    "chest": LARGE_MUSCLE_TARGET,
    "abs": SMALL_MUSCLE_TARGET,
    "shoulders": LARGE_MUSCLE_TARGET,
    "biceps": SMALL_MUSCLE_TARGET,
    "forearms": SMALL_MUSCLE_TARGET,
    "quads": LARGE_MUSCLE_TARGET,
    "back": LARGE_MUSCLE_TARGET,
    "traps": SMALL_MUSCLE_TARGET,
    "triceps": SMALL_MUSCLE_TARGET,
    "glutes": LARGE_MUSCLE_TARGET,
    "hamstrings": LARGE_MUSCLE_TARGET,
    "calves": SMALL_MUSCLE_TARGET,
}


#: A set of a primary muscle counts in full; a secondary muscle counts half.
#:
#: Secondary muscles take real but lesser stimulus, and counting them at full
#: weight would inflate every accessory group — pressing alone would fill the
#: triceps target twice over.
PRIMARY_WEIGHT = 1.0
SECONDARY_WEIGHT = 0.5


#: Categories whose sets count toward weekly muscle volume.
#:
#: The catalog also carries stretches, plyometrics and cardio. They are fully
#: loggable, but grading a hamstring stretch as hamstring training would light
#: up the body map for work that did not happen, so they contribute zero.
VOLUME_CATEGORIES: frozenset[str] = frozenset(
    {"strength", "powerlifting", "olympic weightlifting", "strongman"}
)


CATALOG_PATH = Path(__file__).parent / "data" / "exercises.json"


#: The four hand-written ids this catalog replaced, and their equivalents.
#:
#: Applied by ``flask --app app remap-exercises`` so a database logged against
#: the old catalog keeps its history instead of pointing at ids that no longer
#: resolve. Note the old ``squat`` targeted quads *and* hamstrings for want of a
#: hinge movement; ``Barbell_Squat`` grades hamstrings as secondary, which the
#: catalog now has the vocabulary to say properly.
RETIRED_EXERCISE_IDS: dict[str, str] = {
    "bench_press": "Barbell_Bench_Press_-_Medium_Grip",
    "pull_ups": "Pullups",
    "squat": "Barbell_Squat",
    "sit_ups": "Sit-Up",
}


class CatalogError(RuntimeError):
    """Raised at import when ``exercises.json`` fails its invariants."""


@dataclass(frozen=True)
class Exercise:
    """A loggable movement, its muscles and the facets used to find it.

    The facets are free-exercise-db's own vocabulary (``equipment``,
    ``category``, ``level``, ``force``, ``mechanic``) rather than the
    pattern/modifier split the roadmap sketched — deriving patterns for 873
    movements by hand is the error-prone data entry adopting the dataset was
    meant to avoid, and these serve the picker and Phase 8 equally well.
    """

    id: str
    name: str
    primary: tuple[str, ...]
    secondary: tuple[str, ...]
    equipment: str
    category: str
    level: str
    force: str | None
    mechanic: str | None
    #: Exactly two frames, start and end position, played as a loop on /log.
    images: tuple[str, ...]
    instructions: tuple[str, ...]

    @property
    def muscles(self) -> tuple[str, ...]:
        """Every group this movement trains, primary first.

        Kept so callers that only care *whether* a group was touched —
        ``WorkoutEntry.muscles``, :func:`muscles_for`, the picker's badges —
        did not have to change when the primary/secondary split landed.
        """
        return self.primary + self.secondary

    @property
    def counts_toward_volume(self) -> bool:
        """Whether sets of this movement are graded on the body map."""
        return self.category in VOLUME_CATEGORIES

    def weight_for(self, muscle: str) -> float:
        """Return this movement's volume weight for ``muscle``.

        ``0.0`` for an untargeted group, and for every group when the movement
        is outside :data:`VOLUME_CATEGORIES`.
        """
        if not self.counts_toward_volume:
            return 0.0
        if muscle in self.primary:
            return PRIMARY_WEIGHT
        if muscle in self.secondary:
            return SECONDARY_WEIGHT
        return 0.0

    def to_dict(self) -> dict:
        """The light shape returned by ``GET /api/exercises``.

        Instructions and images are deliberately excluded: the catalog payload
        is fetched whole by the picker and quadruples in size with them.
        ``GET /api/exercises/<id>`` serves the full record.
        """
        return {
            "id": self.id,
            "name": self.name,
            "primary": list(self.primary),
            "secondary": list(self.secondary),
            "muscles": list(self.muscles),
            "equipment": self.equipment,
            "category": self.category,
            "level": self.level,
            "force": self.force,
            "mechanic": self.mechanic,
            "counts_toward_volume": self.counts_toward_volume,
        }

    def to_detail_dict(self, image_base: str = "") -> dict:
        """The full record, with images resolved against ``image_base``."""
        base = image_base.rstrip("/")
        return {
            **self.to_dict(),
            "instructions": list(self.instructions),
            "images": [f"{base}/{path}" if base else path for path in self.images],
        }


def _build(record: dict) -> Exercise:
    return Exercise(
        id=record["id"],
        name=record["name"],
        primary=tuple(record["primary"]),
        secondary=tuple(record["secondary"]),
        equipment=record["equipment"],
        category=record["category"],
        level=record["level"],
        force=record["force"],
        mechanic=record["mechanic"],
        images=tuple(record["images"]),
        instructions=tuple(record["instructions"]),
    )


def _load_catalog(path: Path = CATALOG_PATH) -> dict[str, Exercise]:
    """Read, validate and index the catalog file.

    Raises :class:`CatalogError` rather than returning a partial catalog: a
    silently wrong muscle slug would corrupt every weekly summary that follows.
    """
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:  # pragma: no cover - checked-in data file
        raise CatalogError(
            f"Exercise catalog missing at {path}. "
            "Regenerate it with: python tools/build_exercise_catalog.py"
        ) from exc

    catalog: dict[str, Exercise] = {}
    for record in payload["exercises"]:
        exercise = _build(record)

        if exercise.id in catalog:
            raise CatalogError(f"Duplicate exercise id: {exercise.id!r}.")
        if not exercise.primary:
            raise CatalogError(f"{exercise.id!r} has no primary muscle.")
        if len(exercise.images) != 2:
            raise CatalogError(
                f"{exercise.id!r} has {len(exercise.images)} images; the /log "
                "animation assumes exactly two (start and end position)."
            )
        unknown = set(exercise.muscles) - set(MUSCLE_GROUPS)
        if unknown:
            raise CatalogError(
                f"{exercise.id!r} names unknown muscle groups: {sorted(unknown)}."
            )

        catalog[exercise.id] = exercise

    return catalog


#: The exercises a user may log, keyed by id and ordered by name.
EXERCISES: dict[str, Exercise] = _load_catalog()

#: Every distinct equipment value in the catalog, for the browse drill-down.
EQUIPMENT: tuple[str, ...] = tuple(sorted({e.equipment for e in EXERCISES.values()}))

#: Every distinct category value, ditto.
CATEGORIES: tuple[str, ...] = tuple(sorted({e.category for e in EXERCISES.values()}))


def target_for(muscle: str) -> int:
    """Return the weekly set target for ``muscle``."""
    return MUSCLE_TARGETS.get(muscle, LARGE_MUSCLE_TARGET)


def all_exercises() -> list[Exercise]:
    """Return every exercise in catalog order (alphabetical by name)."""
    return list(EXERCISES.values())


def get_exercise(exercise_id: str) -> Exercise | None:
    """Return the exercise with ``exercise_id``, or ``None`` if unknown."""
    return EXERCISES.get(exercise_id)


def muscles_for(exercise_ids: Iterable[str]) -> set[str]:
    """Return the union of muscle groups trained by ``exercise_ids``."""
    worked: set[str] = set()
    for exercise_id in exercise_ids:
        exercise = EXERCISES.get(exercise_id)
        if exercise is not None:
            worked.update(exercise.muscles)
    return worked


def format_sets(value: float) -> str:
    """Render a weighted set count for display: ``12.5``, but ``12`` not ``12.0``.

    Secondary muscles count half a set, so aggregates are fractional. Mirrored
    by ``formatSets`` in ``app/static/js/ui.js``.
    """
    rounded = round(value, 1)
    return str(int(rounded)) if rounded == int(rounded) else str(rounded)
